package:
  name: 'labinform-datasafe'
  author: 'Mirjam Schröder, Till Biskup'
  author_email: 'till@till-biskup.de'
  year: '2020-24'
  description: 'A local repository for warm research data'
  urls:
    main: 'https://www.labinform.de/'
    documentation: 'https://datasafe.docs.labinform.de/'
    source: 'https://github.com/tillbiskup/labinform-datasafe'
  keywords: [
    'Reproducible research',
    'data storage',
    'repository',
    'warm research data',
    'checksums',
  ]
  install_requires: [
    'flask',
    'oyaml',
    'requests',
  ]
  license: BSD
documentation:
  logo: 'logo.png'
  favicon: 'labinform-favicon.ico'
  language: en
options:
  logging: true
  git: true
  gui: false
